[FIX] Necessario reboot device dopo 'Ripristino SDK'
noiapp/noi-app-android pull request #29
Opened 2020-05-02 17:24 UTC by mauriziopapini

fix issue #20

2020-05-03 11:29 UTC, mdecandia81 commented
Fix provata su 
Device A: Samsung A8 (Android 9) - Segnalata infezione
Device B: Xiaomi Mi PAD 4 (Android 8.1.0) - Ricevuta notifica possibile contagio

Tipo Test: Verificato ripresa BLE handshake e segnalazione possible contagio  dopo "Ripristino SDK" su entrambi i device.

Esito Test: SUCCESS.

2020-05-03 12:28 UTC, mauriziopapini commented
Grazie @mdecandia81!

2020-05-03 14:46 UTC, samuele794 approved these changes
si può applicare, ovviamente in caso il la PR della discovery (o altre iniziative) porteranno alla rimozione della modifica, perchè automatizzata dall'SDK

2020-05-04 07:34 UTC, Magicianred commented
Come segnalato ed anticipare da Samuele, ora ci sono conflitti da risolvere nel merge prima di applicare

2020-05-04 08:57 UTC, mauriziopapini commented
Ho allineato la PR

2020-05-04 12:03 UTC, samuele794 commented
Ciao @mauriziopapini , 
il sync impostato a 10 secondi deve funzionare globalmente nell'app (in modalità di debug ovviamente)?

2020-05-05 13:21 UTC, mauriziopapini commented
Ciao @samuele794!
Sì a mio avviso il sync forzato dovrebbe rimanere attivo, ma questo è il mio modo di vedere. Che ne pensate?
Maurizio

2020-05-05 14:16 UTC, silicia-apps commented
Anche per me dovrebbe rimanere attivo, ho messo l'autodisabilitazione solo perchè appena si cambiava pagina non funzionava più e occorreva chiudere e riaprire l'applicazione. Forse è lo stesso problema che occorreva con il ripristino dell'sdk perchè quando avevo il codice sulla mainActivity funzionava anche ad applicazione chiusa. Più tardi provo la soluzione di Maurizio e vedo se con essa si può risolvere anche il problema del sync.

2020-05-05 14:38 UTC, samuele794 requested changes
Ciao @mauriziopapini ,
attualmente devo rigettarti la modifica.
Facendo questo, il TimerTask funzionerà finché si troverà nella schermata.

Ti consiglio di convertire al JobScheduler di android:

- https://developer.android.com/reference/android/app/job/JobScheduler
- https://developer.android.com/reference/android/app/job/JobInfo.Builder
- https://developer.android.com/reference/android/app/job/JobService

Se vuoi del supporto avvisami

2020-05-05 14:57 UTC, mauriziopapini commented
Ciao @samuele794 e grazie per la precisazione.
Sì voglio supporto anzi se hai chiaro e puoi far tu sono contentissimo, l'implementazione essere inclusa solo per il debug (DebugFrame).

Una domanda: questa però dovrebbe riguardare la PR https://github.com/noiapp/noi-app-android/pull/25 dove veniva inserito il sync ormai chiusa (dopo mia review). Propongo di votare: riaprire la PR relativa, aprirne una nuova oppure chiudere qui la segnalazione che è corretta.
Delle varie opzion non mi dispiacerebbe aprire una issue e chiuderla con una PR specifica.
Che ne pensate @Magicianred  @samuele794  @silicia-apps ?

2020-05-05 15:08 UTC, silicia-apps commented
il timertask è stato usato nella PR #25 non in questa, comunque funziona nel senso che continua ad eseguire i task anche abbandonando il DebugFrame, il problema è legato secondo me al context (le chiamate al sync non andavano più correttamente), volevo provare con la soluzione usata da maurizio per recuperare il context, potrei farlo come nuova pr su una nuova issue per fare funzionare il ping anche con l'app in background. Magari insieme riusciamo a farlo funzionare, io non sono molto pratico di android.

2020-05-05 15:58 UTC, Magicianred commented
Se ho capito bene nella #25 che è stata chiusa c'è un possibile (o concreto problema, bug) mentre questa PR #29  è di per se corretta (atomicamente parlando).

Se è così io direi di chiudere questa, mergiarla, aprire una Issue con la problematica riscontrata a posteriori nella #25 e procedere con una PR nuova per coprire quella situazione, che potrebbe anche andare a riguardare questa PR.

Discorso diverso se Samuele dice che questa PR introduce un errore nella parte di codice di questa funzionalità, non nell'altra. 

Questo secondo me, voi avete più chiara la situazione nel codice e uno fra Francesco e Samuele deve dare il parere tecnico... Samuele è contrario, ma se Francesco è daccordo può approvarla e si procede con una nuova PR per risolvere il caso della #25.

2020-05-05 16:18 UTC, silicia-apps commented
Stasera provo questa per vedere se l'sdk riparte e l'approvo, ma penso che Samuele sarà d'accordo visto che aveva un appunto solo su una parte della #25 (a meno che c'è qualche problema tecnico che a me sfugge).
Nella 25 non è che c'è un vero e proprio bug mi sono accorto che funzionava solo sul DebugFrame e ho fatto in modo di disabilitarla all'uscita (vedi tasto che va in off automaticamente), quindi è stata rilasciata come funzionante solo da lì. Se serve fare in modo che funzioni a prescindere dalla activity aperta si può aprire una nuova issue come nuova funzionalità. Posso rilavorarci io (ho intenzione di provare a passare il context recuperato da maurizio come parametro). Se non funziona magari con samuele e maurizio riusciamo a trovare la soluzione.

2020-05-05 20:14 UTC, silicia-apps approved these changes
Provato ripristino sdk e successivo riavvio tracciatura avvenuto con successo. test: ok

2020-05-05 20:28 UTC, Magicianred approved these changes
silicia-apps left a comment
Provato ripristino sdk e successivo riavvio tracciatura avvenuto con successo. test: ok

Approvo per Francesco che non gli salva la review

2020-05-06 07:38 UTC, merged